### ISSUE TITLE
How to run on server

### ISSUE THREAD

**Issue by ankitkatmore** [nghuyong/rasa-faq-bot#15]
Hello, 

Can you let me know how can i run these on server.

**Comment by ankitkatmore** [comment]
is there any update?

**Comment by itrare** [comment]
@ankitkatmore  It is totally depends upon on which server u are going to use. But for basic you can do following steps to deploy it.
1. Make virtual env in your server in that u can install tensorflow 1.15 and all required libs.
Right now in this repo Bert has not been used since select_pretrained is true so it's is using sentence transformer of pytorch. So for it u can download pretrained model and give the unzipped path by replacing 'bert-base-nli-means'.
Now u can use it with sentence transformer and it gives very good results.
U can search model on internet to download.
If u are not getting it I will give u some code and link to download
But pls try first.

**Comment by sreenathmurali** [comment]
Is it working with latest RASA?

**Comment by nghuyong** [comment]
No, it may not work on the latest RASA.
